import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { Toaster } from "react-hot-toast";
import "./globals.css";
import BottomNavBar from "./components/BottomNavBar";
import SessionProvider from "./components/SessionProvider";
import { AuthLoadingOverlay } from "./components/AuthLoadingOverlay";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <SessionProvider>
          <Toaster
            position="top-center"
            toastOptions={{
              duration: 3000,
              style: {
                background: 'rgba(15, 23, 42, 0.95)',
                color: '#e2e8f0',
                border: '1px solid rgba(255, 255, 255, 0.1)',
                borderRadius: '12px',
                backdropFilter: 'blur(8px)',
              },
              success: {
                iconTheme: {
                  primary: '#34d399',
                  secondary: '#0f172a',
                },
              },
              error: {
                iconTheme: {
                  primary: '#f87171',
                  secondary: '#0f172a',
                },
              },
            }}
          />
          <AuthLoadingOverlay />
          <main>{children}</main>
          <BottomNavBar />
        </SessionProvider>
      </body>
    </html>
  );
}
